name: Deploy Astro site to Pages

on:
  push:
    branches: [ publish ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  BUILD_PATH: "."

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: ${{ env.BUILD_PATH }}/pnpm-lock.yaml

      - name: Setup Pages (获取基础路径)
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build with Astro
        run: |
          pnpm run build \
            --site "${{ steps.pages.outputs.origin }}" \
            --base "${{ steps.pages.outputs.base_path }}"
        working-directory: ${{ env.BUILD_PATH }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  trigger-for-spszerone-github-io:
    name: Trigger for Repo spszerone.github.io Deployment
    runs-on: ubuntu-latest
    # needs: deploy
    steps:
      - name: Dispatch to Repo spszerone.github.io
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.spszerone_github_io_PUBLISH_PAT }}
          repository: SPSZerone/spszerone.github.io
          event-type: update-from-astro-theme-linky-tree
